#!/bin/bash
# Regenerates THIRD_PARTY_NOTICES.md from three sources:
#   1. licenses/HEADER.md + licenses/vendored/*.txt — hand-maintained notices
#      for the C/C++ components Cargo cannot see (llama.cpp, whisper.cpp,
#      sherpa-onnx, onnxruntime, WebRTC APM, SQLCipher, OpenSSL).
#   2. cargo-about over src-tauri/Cargo.lock (config: src-tauri/about.toml,
#      template: src-tauri/about.hbs).
#   3. license-checker-rseidelsohn over the production npm dependencies.
#
# CI runs this and fails if the committed file differs, so re-run it after
# any dependency change:  bash scripts/gen-third-party-notices.sh
#
# Requires: cargo-about (brew install cargo-about | cargo install cargo-about),
# and `npm ci` having been run (for the npm checker).
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/THIRD_PARTY_NOTICES.md"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

if ! cargo about --version >/dev/null 2>&1; then
  echo "gen-third-party-notices: cargo-about not found (brew install cargo-about)" >&2
  exit 1
fi

{
  cat "$ROOT/licenses/HEADER.md"
  echo
  for f in "$ROOT"/licenses/vendored/*.txt; do
    name="$(basename "$f" .txt)"
    echo "### $name"
    echo
    echo '```'
    cat "$f"
    echo '```'
    echo
  done

  echo "## Rust crates"
  echo
  echo "Generated by cargo-about from \`src-tauri/Cargo.lock\` (normal dependencies"
  echo "for \`aarch64-apple-darwin\`; build and dev dependencies excluded). Crates"
  echo "are grouped by license text."
  echo
  (cd "$ROOT/src-tauri" && cargo about generate -c about.toml about.hbs -o "$TMP/rust.md" >/dev/null)
  cat "$TMP/rust.md"

  echo "## npm packages"
  echo
  echo "Production dependencies of the web frontend, as bundled into the app"
  echo "(license-checker-rseidelsohn over \`package-lock.json\`). Full license"
  echo "texts ship in each package's \`node_modules\` directory and repository."
  echo
  (cd "$ROOT" && npx --no-install license-checker-rseidelsohn \
      --production --excludePrivatePackages --json > "$TMP/npm.json")
  python3 - "$TMP/npm.json" <<'PY'
import json, sys
data = json.load(open(sys.argv[1]))
print("| Package | License | Copyright | Repository |")
print("| --- | --- | --- | --- |")
for key in sorted(data, key=str.lower):
    d = data[key]
    lic = d.get("licenses", "")
    if isinstance(lic, list):
        lic = ", ".join(lic)
    cp = (d.get("copyright") or "").replace("|", "\\|").strip()
    repo = d.get("repository") or ""
    print(f"| {key} | {lic} | {cp} | {repo} |")
PY
} > "$TMP/out.md"

# Strip trailing whitespace so the diff check is stable across tools.
sed -e 's/[[:space:]]*$//' "$TMP/out.md" > "$OUT"
echo "gen-third-party-notices: wrote $OUT ($(wc -l < "$OUT" | tr -d ' ') lines)"
